from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

import ShortestRoute_rc
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.resize(820, 455)
        MainWindow.setWindowIcon(QIcon('./pictures/ou_logo.jpg'))
        MainWindow.setStyleSheet("background-color: #123456;")

        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")

        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(20, 10, 781, 411))
        self.frame.setStyleSheet("background-color: white;")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)

        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(285, 0, 496, 411))
        self.label.setStyleSheet(u"background-image: url(:/newPrefix/Map.jpg);")
        self.label.setPixmap(QPixmap(u":/newPrefix/Map.jpg"))
        self.label.setScaledContents(True)
        self.label.setTextInteractionFlags(Qt.NoTextInteraction)

        self.comboBox_Start = QComboBox(self.frame)
        self.comboBox_Start.addItem("")
        self.comboBox_Start.addItem("")
        self.comboBox_Start.addItem("")
        self.comboBox_Start.addItem("")
        self.comboBox_Start.addItem("")
        self.comboBox_Start.addItem("")
        self.comboBox_Start.addItem("")
        self.comboBox_Start.addItem("")
        self.comboBox_Start.addItem("")
        self.comboBox_Start.addItem("")
        self.comboBox_Start.addItem("")
        self.comboBox_Start.addItem("")
        self.comboBox_Start.addItem("")
        self.comboBox_Start.addItem("")
        self.comboBox_Start.addItem("")
        self.comboBox_Start.setObjectName(u"comboBox_Start")
        font = QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.comboBox_Start.setFont(font)
        self.comboBox_Start.setGeometry(QRect(140, 10, 125, 25))

        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 10, 130, 25))
        font = QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setPointSize(12)
        self.label_2.setFont(font)

        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 60, 130, 25))
        font = QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setPointSize(12)
        self.label_3.setFont(font)

        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 190, 61, 20))
        font = QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setPointSize(12)
        self.label_4.setFont(font)

        self.pushButton = QPushButton(self.frame, clicked=self.raceCar)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(30, 110, 215, 51))
        self.pushButton.setStyleSheet("background-color: #99A3A4;")
        font = QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setPointSize(12)
        self.pushButton.setFont(font)

        self.comboBox_Dest = QComboBox(self.frame)
        self.comboBox_Dest.addItem("")
        self.comboBox_Dest.addItem("")
        self.comboBox_Dest.addItem("")
        self.comboBox_Dest.addItem("")
        self.comboBox_Dest.addItem("")
        self.comboBox_Dest.addItem("")
        self.comboBox_Dest.addItem("")
        self.comboBox_Dest.addItem("")
        self.comboBox_Dest.addItem("")
        self.comboBox_Dest.addItem("")
        self.comboBox_Dest.addItem("")
        self.comboBox_Dest.addItem("")
        self.comboBox_Dest.addItem("")
        self.comboBox_Dest.addItem("")
        self.comboBox_Dest.addItem("")
        self.comboBox_Dest.setObjectName(u"comboBox_Dest")
        font = QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.comboBox_Dest.setFont(font)
        self.comboBox_Dest.setGeometry(QRect(140, 60, 125, 25))

        self.tableWidget = QTableWidget(self.frame)
        if (self.tableWidget.columnCount() < 2):
            self.tableWidget.setColumnCount(2)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(10, 220, 260, 181))
        self.tableWidget.setStyleSheet("border: 1px solid black;")
        font = QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.tableWidget.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setStyleSheet("background-color: white; color: black;")
        self.menubar.setGeometry(QRect(0, 0, 640, 24))
        self.options = self.menubar.addMenu("Options")
        self.home = QAction("Home")
        self.home.setIcon(QIcon('./pictures/home.png'))
        self.home.triggered.connect(self.homePressed)
        self.help = QAction("Help")
        self.help.setIcon(QIcon('./pictures/question.png'))
        self.help.triggered.connect(self.helpPressed)
        self.options.addAction(self.home)
        self.options.addAction(self.help)



        MainWindow.setMenuBar(self.menubar)
        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi
    def raceCar(self):
        print("racecar algorithm called")

    def homePressed(self):
        import homePage
        self.homeWindow = QtWidgets.QMainWindow()
        self.homeui = homePage.Ui_MainWindow()
        self.homeui.setupUiHome(self.homeWindow)
        self.homeWindow.show()


    def helpPressed(self):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setWindowIcon(QtGui.QIcon('./pictures/question.png'))
        msg.setWindowTitle("Help: Transportation Management")
        msg.setText("How to use transportation Management window described ...")
        msg.exec_()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Transportation Management"))
        self.label.setText("")
        self.comboBox_Start.setItemText(0, QCoreApplication.translate("MainWindow", u"The Shire", None))
        self.comboBox_Start.setItemText(1, QCoreApplication.translate("MainWindow", u"Bree", None))
        self.comboBox_Start.setItemText(2, QCoreApplication.translate("MainWindow", u"RivenDell", None))
        self.comboBox_Start.setItemText(3, QCoreApplication.translate("MainWindow", u"Gundabad", None))
        self.comboBox_Start.setItemText(4, QCoreApplication.translate("MainWindow", u"Mirkwood", None))
        self.comboBox_Start.setItemText(5, QCoreApplication.translate("MainWindow", u"Lake Town", None))
        self.comboBox_Start.setItemText(6, QCoreApplication.translate("MainWindow", u"Erebor", None))
        self.comboBox_Start.setItemText(7, QCoreApplication.translate("MainWindow", u"Lake Town", None))
        self.comboBox_Start.setItemText(8, QCoreApplication.translate("MainWindow", u"Moria", None))
        self.comboBox_Start.setItemText(9, QCoreApplication.translate("MainWindow", u"Isengard", None))
        self.comboBox_Start.setItemText(10, QCoreApplication.translate("MainWindow", u"Helms Deep", None))
        self.comboBox_Start.setItemText(11, QCoreApplication.translate("MainWindow", u"Minas Tirith", None))
        self.comboBox_Start.setItemText(12, QCoreApplication.translate("MainWindow", u"Minas Morgul", None))
        self.comboBox_Start.setItemText(13, QCoreApplication.translate("MainWindow", u"Dead Marshes", None))
        self.comboBox_Start.setItemText(14, QCoreApplication.translate("MainWindow", u"Mount Doom", None))

        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Start :", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Destination :", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Route", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Submit", None))
        self.comboBox_Dest.setItemText(0, QCoreApplication.translate("MainWindow", u"The Shire", None))
        self.comboBox_Dest.setItemText(1, QCoreApplication.translate("MainWindow", u"Bree", None))
        self.comboBox_Dest.setItemText(2, QCoreApplication.translate("MainWindow", u"RivenDell", None))
        self.comboBox_Dest.setItemText(3, QCoreApplication.translate("MainWindow", u"Gundabad", None))
        self.comboBox_Dest.setItemText(4, QCoreApplication.translate("MainWindow", u"Mirkwood", None))
        self.comboBox_Dest.setItemText(5, QCoreApplication.translate("MainWindow", u"Lake Town", None))
        self.comboBox_Dest.setItemText(6, QCoreApplication.translate("MainWindow", u"Erebor", None))
        self.comboBox_Dest.setItemText(7, QCoreApplication.translate("MainWindow", u"Lake Town", None))
        self.comboBox_Dest.setItemText(8, QCoreApplication.translate("MainWindow", u"Moria", None))
        self.comboBox_Dest.setItemText(9, QCoreApplication.translate("MainWindow", u"Isengard", None))
        self.comboBox_Dest.setItemText(10, QCoreApplication.translate("MainWindow", u"Helms Deep", None))
        self.comboBox_Dest.setItemText(11, QCoreApplication.translate("MainWindow", u"Minas Tirith", None))
        self.comboBox_Dest.setItemText(12, QCoreApplication.translate("MainWindow", u"Minas Morgul", None))
        self.comboBox_Dest.setItemText(13, QCoreApplication.translate("MainWindow", u"Dead Marshes", None))
        self.comboBox_Dest.setItemText(14, QCoreApplication.translate("MainWindow", u"Mount Doom", None))

        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Realms", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Distance", None));
    # retranslateUi
